---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: please enter the target host IP
    private: no
  tasks:
    - add_host:
        name: "{{ item }}"
        groups: dynamically_created_hosts
      with_items: "{{ target_host.split(',') }}"

- hosts: dynamically_created_hosts
  become: yes
  roles:
#    - install_zabbix_ag
#    - zabbix_active
    - astra_apt_repo
    - apt_upgrade_pack
    - apt_install_pack
    - mkuser
    - ssh_root_key
    - ntp
    - alias_ll

