---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: please enter the target host IP
    private: no
  tasks:
    - add_host:
        name: "{{ item }}"
        groups: dynamically_created_hosts
      with_items: "{{ target_host.split(',') }}"

#- hosts: dynamically_created_hosts
- hosts: bind
  roles:
#    - ssh_root_key
    - ssh_secure
